---
- name: Install SELinux python3 tools
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ selinux_tools_packages }}"

- name: Enable SELinux
  ansible.posix.selinux:
    policy: targeted
    state: "{{ state_first_selinux }}"
  register: result

- name: Reboot machine post SELinux Permissive
  reboot:
    pre_reboot_delay: 5
    reboot_timeout: 100

- name: Enable SSH Port SELinux
  community.general.seport:
    ports: "{{ port_ssh_selinux }}"
    proto: tcp
    setype: ssh_port_t
    state: present

- name: Enable SELinux
  ansible.posix.selinux:
    policy: targeted
    state: "{{ state_finish_selinux }}"
  register: result

- name: Reboot machine post SELinux Enforcing
  reboot:
    pre_reboot_delay: 5
    reboot_timeout: 100

# - name: Disable Special Permissions
#   ansible.builtin.command: rttahc -a /usr/local/dcon/users_historylogs/*

# - name: Setting SELinux Context
#   community.general.sefcontext:
#     target: '/usr/local/dcon/users_historylogs(/.*)?'
#     seuser: system_u
#     setype: usr_t
#     state: present

# - name: Apply new SELinux file context to filesystem
#   ansible.builtin.command: restorecon -R -v /usr/local/dcon/users_historylogs
#   register: restorecon_cmd
#   changed_when: '"Would relabel" in restorecon_cmd.stdout'
#   check_mode: no

# - name: Enable Special Permissions
#   ansible.builtin.command: rttahc +a /usr/local/dcon/users_historylogs/*

