---
- name: Enable SELinux
  selinux:
    policy: targeted
    state: "{{ state_first_selinux }}"
  register: selinux_permissive_status

- name: Reboot machine post SELinux Permissive
  reboot:
    pre_reboot_delay: 5
    reboot_timeout: 100

- name: Subscription Manager Refresh
  command: subscription-manager refresh
        
- name: Install SELinux python3 tools
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ selinux_tools_packages }}"
  register: selinux_tools_status

- name: Enable SSH Port SELinux
  seport:
    ports: "{{ port_ssh_selinux }}"
    proto: tcp
    setype: ssh_port_t
    state: present
  register: selinux_ssh_port

- name: Disable Special Permissions
  command: rttahc -a /usr/local/dcon/users_historylogs/*

- name: Setting SELinux Context
  sefcontext:
    target: '/usr/local/dcon/users_historylogs(/.*)?'
    seuser: system_u
    setype: usr_t
    state: present

- name: Apply new SELinux file context to filesystem
  command: restorecon -R -v /usr/local/dcon/users_historylogs
  register: restorecon_cmd
  changed_when: '"Would relabel" in restorecon_cmd.stdout'
  check_mode: no

- name: Enable Special Permissions
  command: rttahc +a /usr/local/dcon/users_historylogs/*

- name: Enable SELinux
  selinux:
    policy: targeted
    state: "{{ state_finish_selinux }}"
  register: selinux_enforcing_status

- name: Reboot machine post SELinux Enforcing
  reboot:
    pre_reboot_delay: 5
    reboot_timeout: 100
