---
# handlers file for aide
- name: Execute aide
  command: /sbin/aide --init
  notify: 
  - mover database

- name: mover database
  ansible.builtin.command: mv /var/lib/aide/{{ aide_new_db }} /var/lib/aide/{{ aide_db }}