---
# handlers file for aide
- name: Execute aide
  shell: /sbin/aide --init
  notify: 
  - mover database

- name: mover database
  shell: mv /var/lib/aide/{{ aide_new_db }} /var/lib/aide/{{ aide_db }}