---

- name: Diretorio temporario yum
  file:
    path: /opt/yum/x86_64/7Server
    owner: root
    group: root
    state: directory
    mode: u+rx,g-rx,o-rwx

- name: Subscription Manager Refresh
  command: subscription-manager refresh
  
- name: Yum Clean All
  shell: "yum clean all"

- name: YUM - Update Bugfix Packages
  yum:
    name: '*'
    conf_file: files/yum.conf
    state: latest
    bugfix: Yes
    exclude: 'glusterfs*'
    # update_cache: true
  register: yum_output_bugfix  

- name: Yum Clean All
  shell: "yum clean all"

- name: YUM - Update Security Packages
  yum:
    name: '*'
    conf_file: files/yum.conf
    state: latest
    security: Yes
    exclude: 'glusterfs*'
    # update_cache: true
  register: yum_output_security  

- name: Yum Clean All
  shell: "yum clean all"

- name: YUM - Update All Packages
  yum:
    name: '*'
    conf_file: files/yum.conf
    state: latest
    exclude: 'glusterfs*'
    # update_cache: true
  register: yum_output_other  

- name: Yum Clean All
  shell: "yum clean all"

- name: Apagar Diretorio Temporario
  file:
    path: /opt/yum/x86_64/7Server
    state: absent

- name: Reboot Machine Post Yum Updates
  reboot:
    pre_reboot_delay: 5
    reboot_timeout: 500