---
- name: Yum Clean All
  ansible.builtin.command: "yum clean all"

- name: YUM - Update Bugfix Packages
  ansible.builtin.:
    name: '*'
    state: latest
    bugfix: Yes
    exclude: 'glusterfs*'
    update_cache: true
  register: yum_output  

- name: YUM - Update Security Packages
  ansible.builtin.:
    name: '*'
    state: latest
    security: Yes
    exclude: 'glusterfs*'
    update_cache: true
  register: yum_output  

- name: YUM - Update All Packages
  ansible.builtin.:
    name: '*'
    state: latest
    exclude: 'glusterfs*'
    update_cache: true
  register: yum_output  

- name: Display yum output
  debug: 
    var: yum_output.results
    verbosity: 2

- name: Reboot Machine Post Yum Updates
  reboot:
    pre_reboot_delay: 5
    reboot_timeout: 100