---
- name: YUM - Update Bugfix Packages
  yum:
    name: '*'
    state: latest
    bugfix: yes
    exclude: 'glusterfs*'
    update_cache: true
  register: yum_output  

- name: YUM - Update Security Packages
  yum:
    name: '*'
    state: latest
    security: yes
    exclude: 'glusterfs*'
    update_cache: true
  register: yum_output  

- name: YUM - Update All Packages
  yum:
    name: '*'
    state: latest
    exclude: 'glusterfs*'
    update_cache: true
  register: yum_output  

- name: Display yum output
  debug: 
    var: yum_output.results
    verbosity: 2
