---
- name: Subscription Manager Refresh
  command: subscription-manager refresh
  
- name: Yum Clean All
  command: "yum clean all"

- name: YUM - Update Bugfix Packages
  yum:
    name: '*'
    state: latest
    bugfix: Yes
    exclude: 'glusterfs*'
    update_cache: true
  register: yum_output_bugfix  

- name: Yum Clean All
  command: "yum clean all"

- name: YUM - Update Security Packages
  yum:
    name: '*'
    state: latest
    security: Yes
    exclude: 'glusterfs*'
    update_cache: true
  register: yum_output_security  

- name: Yum Clean All
  command: "yum clean all"

- name: YUM - Update All Packages
  yum:
    name: '*'
    state: latest
    exclude: 'glusterfs*'
    update_cache: true
  register: yum_output_other  

- name: Yum Clean All
  command: "yum clean all"

- name: Reboot Machine Post Yum Updates
  reboot:
    pre_reboot_delay: 5
    reboot_timeout: 500